### ISSUE TITLE
cm-12.1 branch

### ISSUE THREAD

**Issue by tycoo** [omkxr/ghost#4]
Hey Megatron,

do you like to set a branch "cm-12.1" at https://github.com/Megatron007/ghost/commit/90ac803e842ec8dc2b42b0f397c0395558a61ee0

I would like to push some kernel updates then.

regards

**Comment by omkxr** [comment]
done :) go for it

**Comment by tycoo** [comment]
´thx but do it at the commit plz: https://github.com/Megatron007/ghost/commit/90ac803e842ec8dc2b42b0f397c0395558a61ee0

the last commit by cyanogenmod branch
